### ISSUE TITLE
Alternative to CidCe from featuretools_tsfresh_primitives v0.1.3

### ISSUE THREAD

**Issue by josemariagarcia95** [FeatureLabs/featuretools-tsfresh-primitives#104]
I'm learning how to use Featuretools and I'm following a [tutorial ](https://github.com/Featuretools/predict-remaining-useful-life/blob/master/Advanced%20Featuretools%20RUL.ipynb) which, at some point, uses the following snippet.

```python
from featuretools.tsfresh import CidCe
import featuretools as ft

fm, features = ft.dfs(
    entityset=es,
    target_entity='engines',
    agg_primitives=['last', 'max', CidCe(normalize=False)],
    trans_primitives=[],
    chunk_size=.26,
    cutoff_time=cutoff_time_list[0],
    max_depth=3,
    verbose=True,
)

fm.to_csv('advanced_fm.csv')
fm.head()
```
However, apparently CidCe was on featuretools_tsfresh_primitives version 0.1.3, but it's not anymore, and since I don't know what it is I don't know how to try to substitute it (I wanna use it the last version of tsfresh, which is 1.0.2.

**Comment by thehomebrewnerd** [comment]
What error are you getting? I believe CidCe should still be a valid primitive for newer versions.

**Comment by josemariagarcia95** [comment]
This is the error

ImportError: cannot import name 'CidCe' from 'tsfresh' (C:\Users\josemaria.garcia\AppData\Local\anaconda3\lib\site-packages\tsfresh\__init__.py)

**Comment by josemariagarcia95** [comment]
@thehomebrewnerd  I checked the [docs ](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.html) of `tfresh` but CidCe is not there in the current version.

**Comment by thehomebrewnerd** [comment]
> @thehomebrewnerd I checked the [docs ](https://tsfresh.readthedocs.io/en/latest/api/tsfresh.html) of `tfresh` but CidCe is not there in the current version.

I think it's there: https://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#tsfresh.feature_extraction.feature_calculators.cid_ce

Everything seems to work fine for me, so there might be something wrong with your install perhaps?

```
>>> import featuretools as ft
>>> ft.__version__
'1.27.0'
>>> import featuretools_tsfresh_primitives as ftts
>>> ftts.__version__
'1.0.2'
>>> import tsfresh as ts
>>> ts.__version__
'0.20.1'
>>> from featuretools.tsfresh import CidCe
>>> CidCe(normalize=False)
<featuretools_tsfresh_primitives.primitives.cid_ce.CidCe object at 0x104f54130>
```

Can you confirm the versions you are using for all these: `featuretools`, `featuretools_tsfresh_primitives` and `tsfresh`?

**Comment by josemariagarcia95** [comment]
I've just seen that I was trying to import CidCe from tsfresh, like from `tsfresh import CidCe`, so that was the problem. 
![Captura de pantalla 2023-07-27 170914](https://github.com/alteryx/featuretools-tsfresh-primitives/assets/14859356/5f92403f-ac2b-44ba-b499-c6772db24895)

You can close this issue now, but now I have a question if you don't mind: what's the different then between `featuretools.tsfresh` and `tsfresh`? Are they separated modules with no relationship besides being used for the same purpose?

**Comment by josemariagarcia95** [comment]
Also, any idea why this could happen in a notebook?
![image](https://github.com/alteryx/featuretools-tsfresh-primitives/assets/14859356/5669fd51-880a-4b45-a196-88c4de4f5080)

**Comment by thehomebrewnerd** [comment]
@josemariagarcia95 No, I'm not sure. I am not having that problem.

**Comment by thehomebrewnerd** [comment]
> You can close this issue now, but now I have a question if you don't mind: what's the different then between `featuretools.tsfresh` and `tsfresh`? Are they separated modules with no relationship besides being used for the same purpose?

@josemariagarcia95 `tsfresh` is the base library that contains the core functions that do the numeric calculations. `featuretools-tsfresh-primitives` is a separate library that wraps the functions in `tsfresh` with some additional code that is needed to use the base `tsfresh` functions with Featuretools inside of deep feature synthesis. Without the wrapper library Featuretools cannot use the `tsfresh` functions to calculate features.
